Clean up some more bin2c calls from the Makefile
n64decomp/mk64 pull request #286
Opened 2023-01-12 00:09 UTC by Tmcg2

Some of these required adding a new operation mode to n64graphics.
This new mode takes an image and a tlut (both as PNGs) and outputs the equivalent CI8 in inc.c form
As mentioned in the commit message, I have left those n64graphics changes in a, shall we say, crusty state in order to bring attention to them. They work fine for our immediate purposes but better names should be made and the new mode should be made more feature complete (for example, handle rgba32).

2023-01-24 05:13 UTC, Tmcg2 commented
I've made my additions to the n64graphics utility a little less crappy. As it stands it works for the purposes of the MK64 project. There are a couple things that could be done to make it more useful to other projects, but unless there's a desire to push these changes to the sm64tools project, I don't see much value in pursuing them.

2023-01-29 08:44 UTC, MegaMech requested changes

2023-01-29 08:44 UTC, MegaMech commented on assets.json
> +"textures/gTextureGreenShell06.rgba16.ci8.png": {"meta":{"dims":[32,32], "pal":["0x4E38", "0x132B50"]}, "offsets": {"us":["0x68F96C", "0x00000"]}},
duplicate name

2023-01-29 15:20 UTC, Tmcg2 commented on assets.json
> +"textures/gTextureGreenShell06.rgba16.ci8.png": {"meta":{"dims":[32,32], "pal":["0x4E38", "0x132B50"]}, "offsets": {"us":["0x68F96C", "0x00000"]}},
Good catch

2023-02-06 05:19 UTC, MegaMech approved these changes

2023-02-07 05:52 UTC, merged