Migrate player emblemb assets
n64decomp/mk64 pull request #326
Opened 2023-07-01 20:39 UTC by Tmcg2

Not sure about the name "emblemb", open to suggestions.

Can't find these textures being used anywhere, might be leftovers
 from an earlier time in the game's development.

2023-07-02 05:49 UTC, MegaMech requested changes

2023-07-02 05:49 UTC, MegaMech commented on assets/player_emblembs.json
> +"gTexturePlayerEmblemb1p": {"output_dir": "player_emblembs", "rom_offset": "0x132B50", "block_offset": "0x17458", "width": 64, "height": 32, "type": "ci8", "tlut": "gTLUTPlayerEmblemb"},
Emblem,  no b

2023-07-02 19:48 UTC, MegaMech submitted a review, later dismissed

2023-07-02 20:17 UTC, MegaMech commented
Jenkins is down for maintenance.

2023-07-02 20:29 UTC, Tmcg2 commented
It was good that it reported an error, even if that was a result of Jenkins being down. Had to do some merge resolution when rebasing on master anyway.

2023-07-03 02:40 UTC, MegaMech approved these changes

2023-07-03 02:41 UTC, merged