rename in code_8001F980.c
n64decomp/mk64 pull request #456
Opened 2023-10-11 17:45 UTC by coco875

reopen because I rename the branch

2023-10-11 19:26 UTC, coco875 commented
who are before https://github.com/n64decomp/mk64/pull/454

2023-10-14 01:20 UTC, MegaMech requested changes

2023-10-14 01:20 UTC, MegaMech commented on src/code_8001F980.c
> +s8 renderingFramebufferByPlayer[] = {
gRendering...

2023-10-14 02:35 UTC, MegaMech approved these changes

2023-10-14 02:55 UTC, merged