Import some code_80071F00 matches
n64decomp/mk64 pull request #495
Opened 2023-11-10 19:19 UTC by ItzSwirlz

Credit goes to Taggerung

2023-11-10 20:23 UTC, Tmcg2 commented
My only request would be to put the prototypes for the matched functions and any `extern`d variables in the appropriate header file. That way they can be picked up as `mips_to_c` context which helps makes its output more accurate.

2023-11-14 16:21 UTC, MegaMech requested changes

2023-11-14 16:21 UTC, MegaMech commented on src/code_80071F00.c
>  extern s8 D_801658C6;
Please delete these two externs now that they are in the header.

2023-11-14 16:21 UTC, MegaMech commented on src/code_80071F00.c
>  extern s32 D_80183EA4;
Please delete this extern now that it's in the header.

2023-11-25 02:11 UTC, MegaMech approved these changes

2023-11-25 02:11 UTC, merged