Match the last 2 data files
n64decomp/mk64 pull request #574
Opened 2024-02-15 04:18 UTC by Tmcg2

The names `some_data` and `some_data_2` are obviously terrible but I don't know what else to call them. I am open to any and all suggestions for improved names.

2024-02-15 04:25 UTC, MegaMech requested changes

2024-02-15 04:25 UTC, MegaMech commented on src/data/some_data_2.c
> +
Name this file `path_spawn_data.c`?

2024-02-23 07:41 UTC, MegaMech submitted a review, later dismissed

2024-02-23 07:47 UTC, MegaMech commented
```c
src/data/some_data.c:185:14: fatal error: assets/onomatopoeia/gTLUTOnomatopoeia.inc.c: No such file or directory
     #include "assets/onomatopoeia/gTLUTOnomatopoeia.inc.c"
```

2024-02-23 15:01 UTC, Tmcg2 commented
Think I fixed it, I had an incorrect path in onomatopoeia asset makefile that was likely causing the tlut .inc.c file to not get generated

2024-02-25 04:45 UTC, MegaMech approved these changes

2024-02-28 15:11 UTC, merged