use github actions instead
n64decomp/mk64 pull request #605
Opened 2024-04-12 23:05 UTC by coco875

2024-04-12 23:12 UTC, coco875 commented
![image](https://github.com/n64decomp/mk64/assets/59367621/d0c62150-c4bb-4a91-8887-d0eb56bcec79)
what it look like once it's merged

2024-04-12 23:20 UTC, coco875 commented
fix non matching being on the second line

2024-04-12 23:48 UTC, MegaMech requested changes

2024-04-12 23:48 UTC, MegaMech commented on README.md
> -```
You're missing ```

2024-04-12 23:48 UTC, MegaMech commented on progress.py
> +    badge_asm_funcs = badge(left_text="ASM functions", right_text=str(TotalGlobalAsmFunctions), right_color="blue")
How do you feel about changing this to WIP functions?

2024-04-12 23:48 UTC, MegaMech commented on README.md
> +status: [![Linux Compile test](https://github.com/n64decomp/mk64/actions/workflows/linux-compile.yml/badge.svg)](https://github.com/n64decomp/mk64/actions/workflows/linux-compile.yml)
Remove `status:` and rename `Linux Compile test` to `Linux compile`.

2024-04-13 00:54 UTC, MegaMech approved these changes

2024-04-13 00:54 UTC, merged