fix typo racing
n64decomp/mk64 pull request #653
Opened 2024-07-30 19:20 UTC by coco875

2024-07-31 01:10 UTC, coco875 commented
don't match

2024-08-01 03:22 UTC, MegaMech requested changes

2024-08-01 03:22 UTC, MegaMech commented on src/racing/memory.c
> -    u32 size = srcStart - dest;
ptrdiff_t

2024-08-01 03:22 UTC, MegaMech commented on src/racing/memory.c
> +    arg0[sGfxSeekPosition].words.w0 = (uintptr_t)(uint8_t)G_ENDDL << 24;
Does this match?

2024-08-01 03:22 UTC, MegaMech commented on src/racing/memory.c
>      gfx[sGfxSeekPosition].words.w1 =
These two lilnes should probably say G_QUAD not G_LINE3D as line3d only exists in the line3d microcode and not in f3dex.

2024-08-02 01:01 UTC, coco875 commented on src/racing/memory.c
> +    arg0[sGfxSeekPosition].words.w0 = (uintptr_t)(uint8_t)G_ENDDL << 24;
yes

2024-08-02 01:04 UTC, coco875 commented on src/racing/memory.c
> -    u32 size = srcStart - dest;
not match with ptrdiff_t

2024-08-16 21:42 UTC, MegaMech approved these changes

2024-08-16 21:42 UTC, MegaMech commented on src/racing/memory.c
> +    uintptr_t tmem;
technically these all shouldn't be uintpr_t but whatevs

2024-08-16 21:42 UTC, merged